on: workflow_dispatch

name: Test comment

jobs:
  test-comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Comment on issue
      id: comment
      uses: ./
      with:
        issue: IssueID
        comment: First comment here!
        type: warning # info | note | success | warning | error
        panelComment: First panel comment here!

    - name: Update comment on issue
      id: update
      uses: ./
      with:
        issue: IssueID
        comment: Second comment here!
        type: success # info | note | success | warning | error
        panelComment: Second panel comment here!
        update: ${{ steps.comment.outputs.id }}
